// obfuscator.js

const { hideConstants } = require("./constant-hider");
const { solveMath } = require("./math-solver");

function obfuscate(source, options = {}) {
  if (typeof source !== "string") {
    throw new TypeError("Source must be a string");
  }

  /*
   * Normalize line endings.
   */
  let code =
    source.replace(/\r\n?/g, "\n");

  const stats = {
    strings: 0,
    numbers: 0,
    booleans: 0
  };

  /*
   * Math solving happens before constant hiding.
   *
   * Example:
   *
   * 10 + 20
   *
   * becomes:
   *
   * 30
   *
   * and then constant-hider can hide 30.
   */
  if (options.solveMath !== false) {
    code = solveMath(code);
  }

  /*
   * Hide constants.
   *
   * The new constant-hider generates:
   *
   * local __S_x = "Hello"
   * local __N_x = 123
   * local __B_x = true
   *
   * instead of:
   *
   * local __S_x = {
   *     "Hello"
   * }
   *
   * followed by:
   *
   * __S_x[1]
   */
  if (options.hideConstants !== false) {
    const result =
      hideConstants(code);

    code = result.source;

    stats.strings =
      result.counts.strings;

    stats.numbers =
      result.counts.numbers;

    stats.booleans =
      result.counts.booleans;

    if (result.header) {
      code =
        result.header +
        "\n\n" +
        code;
    }
  }

  /*
   * Generated-file banner.
   */
  const banner =
    "-- Generated by Luau Obfuscator\n" +
    "-- Local source transformer\n\n";

  return {
    code: banner + code,
    stats
  };
}

module.exports = {
  obfuscate
};
