const { hideConstants } = require("./constant-hider");
const { solveMath } = require("./math-solver");

/*
 * Luau Obfuscator
 *
 * Pipeline:
 *
 * Source
 *   ↓
 * Normalize
 *   ↓
 * Math Solver
 *   ↓
 * Constant Hider
 *   ↓
 * Output Validation
 *
 * This file intentionally does not execute Luau code.
 */

function normalizeSource(source) {
  return source.replace(/\r\n?/g, "\n");
}

/*
 * Remove accidental control characters that must
 * never appear in generated Luau source.
 *
 * We only remove the placeholder-control range used
 * by older versions of the transformer.
 */
function sanitizeOutput(source) {
  if (typeof source !== "string") {
    throw new TypeError(
      "Generated source must be a string"
    );
  }

  /*
   * These characters were previously used as
   * internal placeholders:
   *
   * \x01
   * \x02
   * \x03
   * \x04
   *
   * They are not valid source-level placeholders.
   */
  return source.replace(/[\x01\x02\x03\x04]/g, "");
}

/*
 * Detect broken internal placeholders.
 *
 * Safe textual placeholders are allowed only during
 * transformation and should never survive into final
 * generated code.
 */
function validateOutput(source) {
  if (typeof source !== "string") {
    throw new TypeError(
      "Generated source is not a string"
    );
  }

  const forbiddenControl =
    /[\x00-\x08\x0B\x0C\x0E-\x1F]/;

  if (forbiddenControl.test(source)) {
    throw new Error(
      "Generated Luau contains invalid control characters"
    );
  }

  /*
   * Old placeholder formats should never survive.
   */
  if (
    source.includes("__LUAPROTECT_") ||
    source.includes("__LUANUM_") ||
    source.includes("__LUABOOL_") ||
    source.includes("__LUAMATHPROTECT_") ||
    source.includes("__LUAMATHIDENT_")
  ) {
    throw new Error(
      "Generated Luau contains unresolved internal placeholders"
    );
  }

  return true;
}

function createStats() {
  return {
    strings: 0,
    numbers: 0,
    booleans: 0
  };
}

function obfuscate(source, options = {}) {
  if (typeof source !== "string") {
    throw new TypeError(
      "Source must be a string"
    );
  }

  if (
    options === null ||
    typeof options !== "object"
  ) {
    options = {};
  }

  let code =
    normalizeSource(source);

  const stats =
    createStats();

  /*
   * Step 1:
   * Solve safe constant math expressions.
   *
   * This stage only works with numeric expressions
   * and never executes arbitrary Luau code.
   */
  if (options.solveMath !== false) {
    const solved =
      solveMath(code);

    if (typeof solved !== "string") {
      throw new Error(
        "Math solver returned invalid source"
      );
    }

    code = solved;
  }

  /*
   * Step 2:
   * Hide constants.
   *
   * String / number / boolean constants are moved
   * into generated local tables.
   */
  if (options.hideConstants !== false) {
    const result =
      hideConstants(code);

    if (
      !result ||
      typeof result.source !== "string"
    ) {
      throw new Error(
        "Constant hider returned invalid source"
      );
    }

    code =
      result.source;

    if (
      result.counts &&
      typeof result.counts === "object"
    ) {
      stats.strings =
        Number(result.counts.strings) || 0;

      stats.numbers =
        Number(result.counts.numbers) || 0;

      stats.booleans =
        Number(result.counts.booleans) || 0;
    }

    /*
     * Add constant tables before the source.
     */
    if (
      typeof result.header === "string" &&
      result.header.length > 0
    ) {
      code =
        result.header +
        "\n\n" +
        code;
    }
  }

  /*
   * Step 3:
   * Sanitize accidental legacy control characters.
   *
   * This is a final safety net.
   */
  code =
    sanitizeOutput(code);

  /*
   * Step 4:
   * Validate generated output.
   *
   * Do this BEFORE adding the banner so errors point
   * at the actual generated source.
   */
  validateOutput(code);

  /*
   * Header / banner.
   */
  const banner =
    "-- Generated by Luau Obfuscator\n" +
    "-- Local source transformer\n\n";

  const finalCode =
    banner + code;

  /*
   * Validate the complete final output too.
   */
  validateOutput(finalCode);

  return {
    code: finalCode,
    stats
  };
}

module.exports = {
  obfuscate,
  sanitizeOutput,
  validateOutput
};
