const { hideConstants } = require("./constant-hider");
const { solveMath } = require("./math-solver");

function obfuscate(source, options = {}) {
  if (typeof source !== "string") {
    throw new TypeError("Source must be a string");
  }

  let code = source.replace(/\r\n?/g, "\n");

  const stats = {
    strings: 0,
    numbers: 0,
    booleans: 0
  };

  /*
   * Step 1:
   * Solve safe constant math expressions.
   */
  if (options.solveMath !== false) {
    code = solveMath(code);
  }

  /*
   * Step 2:
   * Move constants into generated tables.
   */
  if (options.hideConstants !== false) {
    const result = hideConstants(code);

    code = result.source;

    stats.strings = result.counts.strings;
    stats.numbers = result.counts.numbers;
    stats.booleans = result.counts.booleans;

    if (result.header) {
      code =
        result.header +
        "\n\n" +
        code;
    }
  }

  /*
   * Header.
   */
  const banner =
    "-- Generated by Luau Obfuscator\n" +
    "-- Local source transformer\n\n";

  return {
    code: banner + code,
    stats
  };
}

module.exports = {
  obfuscate
};
